[[repos]]
repo = "https://github.com/astral-sh/ruff-pre-commit"
rev = "v0.15.12" # Ruff version.
hooks = [
  # Run the linter.
  { id = "ruff-check", args = ["--fix"], types_or = ["python", "pyi"] },

  # Run the formatter.
  { id = "ruff-format", types_or = ["python", "pyi"] },
]


[[repos]]
repo = "local"
hooks = [
  {
    id = "ty",
    name = "ty check",
    language = "system",
    entry = "uv run ty check",
    pass_filenames = false,
    require_serial = true,
  },
]